### ISSUE TITLE
Success and failure call back 

### ISSUE THREAD

**Issue by avinashbanswada** [AniTrend/retrofit-graphql#93]
Hello, Can you please help me achive the feature which we have in Completable class. It does have success, error, complete call back, how can I achive this using your library. I tried using Completable but it only supports Maybe, observer, completable types but using this library the return type of a network call is Response<GraphContainer<*>> which is not present in Completable class. End of the day I want to display the error message in UI if I get any error response, I am following the room architecture, UI layer ->Viewmodel -> Repository -> DAO . Please drop a mail if you don't want to talk this here (avinash.banswada@gmail.com) Thanks in advance, awaiting for you reply.

**Comment by wax911** [comment]
Hi are you talking about this [Completable](http://reactivex.io/RxJava/2.x/javadoc/io/reactivex/Completable.html) in RxJava? If so then all you need to do is to add a call adapter to your retrofit instance that supports RxJava. Please see [RxJava Adapter](https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava)

**Comment by avinashbanswada** [comment]
My retrofit instance already has call adapter. 
fun abc(queryContainerBuilder: QueryContainerBuilder, object: Name?) {
        GlobalScope.launch(Dispatchers.IO) {
            try {
                val dataResponse = service.getDataWithUser(queryContainerBuilder)
                val container: GraphContainer<ResultObject>? = topicsReceivedResponse.body()
                if (dataResponse .isSuccessful && container != null) {
                     //success response
                }else{
                   //error response
            } catch (e: java.lang.Exception) {
                DLog.e(e, "error while getting data")
            }

        }
    }
How I can pass the error and success call back to my UI layer. The success response type is Response<GraphContainer<*>> and failure response is "Resonse{protocol =h2, code=500,message=
}"

**Comment by wax911** [comment]
Alright, I am going to make some general assumptions here. 
- I'll assume that you're using coroutines for you network calls and you already know how they work
- I'll assume you have some general knowledge about how retrofit works
- I'll assume that you're not using RxJava and your `Completable` is just a custom sealed class otherwise I'd probably just use RxJava adapter instead of coroutines   

On to your question: 
> How I can pass the error and success call back to my UI layer. The success response type is Response<GraphContainer<*>> and failure response is "Resonse{protocol =h2, code=500,message=
}"

It seems to me you're asking how to work with retrofit, which is not related to this library as this is just an extension layer on top of that.

Unfortunately I can't give you a simple straight forward answer to this, as this depends what your requirements are. Since you're using this library that suggests you're using a **graphql** endpoint, and if it follows the [specification](http://spec.graphql.org/draft/#sec-Response) then you should use this extension function `io.github.wax911.library.util.getError` on your response object, this will return a list of errors.

What you want to return to your UI layer is honestly up to you, I'll give you an example of how I would do this if I were you.

## State object
```kotlin
/**
 * State representing ongoing, completed or failed requests
 */
sealed class NetworkState {

    object Loading : NetworkState()

    data class Success<T>(
        val data: T
    ) : NetworkState()

    /**
     * Network state for failed requests with an optional message or code
     *
     * @param code The response code from the last request
     * @param heading Heading related to the error message
     * @param message Message to display if any are available
     */
    data class Error(
        val code: Int? = null,
        val heading: String? = null,
        val message: String? = null
    ) : NetworkState()
}
```

## Your function inside your repository

```kotlin
fun abc(queryContainerBuilder: QueryContainerBuilder, object: Name ? ): NetworkState {
    GlobalScope.launch(Dispatchers.IO) {
        return try {
            val dataResponse = service.getDataWithUser(queryContainerBuilder)
            val container: GraphContainer ? = topicsReceivedResponse.body()
            if (dataResponse.isSuccessful && container != null) {
                NetworkState.Success(container)
            } else {
                // found in the package io.github.wax911.library.util
                val errors: List<GraphError>? = dataResponse.getError()
                NetworkState.Error(
                        heading = "Request failed with error",
                        message = errors?.firstOrNull()?.message
                    )
            } catch (e: java.lang.Exception) {
                DLog.e(e, "error while getting data")
                NetworkState.Error(
                    heading = "Error while getting data",
                    message = e.message
                )
            }
        }
    }
}
```

**Other suggestions**

I'd also suggest against using `GlobalScope.*` for your requests and rather convert your function into a suspend function and replace `GlobalScope.*` with `withContext(Dispatchers.IO)` or alternatively just pass in a _Coroutine Scope_ into the function and just use that **scope** instead of **GlobalScope**. Since global scope is not tied to the lifecycle of your repository/viewmodel e.t.c :wink:

**Comment by avinashbanswada** [comment]
thanks much, it helps :)

**Comment by wax911** [comment]
Glad it helped, I'll close this issue now and feel free to re-open it again if you have more questions.
